apiVersion: v1
kind: Service
metadata:
  name: gst-http
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gst-http
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30180
