apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cfgmap
data:
  index-cfgmap: |
    server {
      listen 80;
      listen [::]:80;
      server_name _;
      root /captured;
      location / {
        root /captured/;
        autoindex on;
        autoindex_exact_size off;
        autoindex_format html;
        autoindex_localtime on;
      }
    }
