apiVersion: v1
kind: Deployment
metadata:
  name: testgst-1
  labels:
    app.kubernetes.io/name: gstpipeline-1
spec:
  replicas: 1
  template:
    template:
      spec:
        containers:
        - name: test-infer-1
          image: krickwix/jetson-gst-recorder:jp5-v0.9
          env:
            - name: FPS
              value: "2/1"
            - name: WIDTH
              value: "600"
            - name: HEIGHT
              value: "600"
            - name: RTSP_URL
              value: "rtspt://192.168.0.11:9000/live"
            - name: RTSP_FEED_NAME
              value: 'cam1'
            - name: GST_DEBUG
              value: "1"
            - name: JPEG_QUALITY
              value: "50"
          volumeMounts:
            - mountPath: "/captured"
              name: capture-storage
        - name: test-infer-2
          image: krickwix/jetson-gst-recorder:jp5-v0.9
          env:
            - name: FPS
              value: "2/1"
            - name: WIDTH
              value: "600"
            - name: HEIGHT
              value: "600"
            - name: RTSP_URL
              value: "rtspt://192.168.0.10:9000/live"
            - name: RTSP_FEED_NAME
              value: 'cam2'
            - name: GST_DEBUG
              value: "1"
            - name: JPEG_QUALITY
              value: "50"
          volumeMounts:
            - mountPath: "/captured"
              name: capture-storage
        - name: test-infer-3
          image: krickwix/jetson-gst-recorder:jp5-v0.9
          env:
            - name: FPS
              value: "2/1"
            - name: WIDTH
              value: "600"
            - name: HEIGHT
              value: "600"
            - name: RTSP_URL
              value: "rtspt://192.168.0.61:9000/live"
            - name: RTSP_FEED_NAME
              value: 'cam3'
            - name: GST_DEBUG
              value: "1"
            - name: JPEG_QUALITY
              value: "50"
          volumeMounts:
            - mountPath: "/captured"
              name: capture-storage
        - name: test-infer-4
          image: krickwix/jetson-gst-recorder:jp5-v0.9
          env:
            - name: FPS
              value: "2/1"
            - name: WIDTH
              value: "600"
            - name: HEIGHT
              value: "600"
            - name: RTSP_URL
              value: "rtspt://192.168.0.31:8554/stream1"
            - name: RTSP_FEED_NAME
              value: 'stream1'
            - name: GST_DEBUG
              value: "1"
            - name: JPEG_QUALITY
              value: "50"
          volumeMounts:
            - mountPath: "/captured"
              name: capture-storage
        - name: test-infer-5
          image: krickwix/jetson-gst-recorder:jp5-v0.9
          env:
            - name: FPS
              value: "2/1"
            - name: WIDTH
              value: "600"
            - name: HEIGHT
              value: "600"
            - name: RTSP_URL
              value: "rtspt://192.168.0.31:8554/stream2"
            - name: RTSP_FEED_NAME
              value: 'stream2'
            - name: GST_DEBUG
              value: "1"
            - name: JPEG_QUALITY
              value: "50"
          volumeMounts:
            - mountPath: "/captured"
              name: capture-storage
        - name: test-infer-6
          image: krickwix/jetson-gst-recorder:jp5-v0.9
          env:
            - name: FPS
              value: "2/1"
            - name: WIDTH
              value: "600"
            - name: HEIGHT
              value: "600"
            - name: RTSP_URL
              value: "rtspt://192.168.0.31:8554/stream3"
            - name: RTSP_FEED_NAME
              value: 'stream3'
            - name: GST_DEBUG
              value: "1"
            - name: JPEG_QUALITY
              value: "50"
          volumeMounts:
            - mountPath: "/captured"
              name: capture-storage
        - name: test-infer-7
          image: krickwix/jetson-gst-recorder:jp5-v0.9
          env:
            - name: FPS
              value: "2/1"
            - name: WIDTH
              value: "600"
            - name: HEIGHT
              value: "600"
            - name: RTSP_URL
              value: "rtspt://192.168.0.31:8554/stream4"
            - name: RTSP_FEED_NAME
              value: 'stream4'
            - name: GST_DEBUG
              value: "1"
            - name: JPEG_QUALITY
              value: "50"
          volumeMounts:
            - mountPath: "/captured"
              name: capture-storage
        - name: test-infer-8
          image: krickwix/jetson-gst-recorder:jp5-v0.9
          env:
            - name: FPS
              value: "2/1"
            - name: WIDTH
              value: "600"
            - name: HEIGHT
              value: "600"
            - name: RTSP_URL
              value: "rtspt://192.168.0.31:8554/stream5"
            - name: RTSP_FEED_NAME
              value: 'stream5'
            - name: GST_DEBUG
              value: "1"
            - name: JPEG_QUALITY
              value: "50"
          volumeMounts:
            - mountPath: "/captured"
              name: capture-storage
        volumes:
          - name: capture-storage
            persistentVolumeClaim:
              claimName: pvc-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: testgst-http
  labels:
    app.kubernetes.io/name: gstpipeline-1
spec:
    containers:
    - name: http-server
      image: nginx:1.23.4
      volumeMounts:
        - mountPath: "/captured"
          name: capture-storage
        - name: nginx-cfgmap
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: index-cfgmap
      ports:
      - containerPort: 80
        name: http-port
    volumes:
      - name: capture-storage
        persistentVolumeClaim:
          claimName: pvc-storage
      - name: nginx-cfgmap
        configMap:
          name: nginx-cfgmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cfgmap
data:
  index-cfgmap: |
    server {
      listen 80;
      listen [::]:80;
      server_name _;
      root /captured;
      location / {
        root /captured/;
        autoindex on;
        autoindex_exact_size off;
        autoindex_format html;
        autoindex_localtime on;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: http-service-1
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gstpipeline-1
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30180
